<div class="p-2 table-responsive">
	<table class="table table-bordered table-striped-even header-text" align="center">
		<caption class="font-sm ml-3">List of Sales generated by Point Of Sale!</caption>
		<thead class="thead-light">
			<tr>
				<th>Product Name</th>
				<th>Quantity</th>
				<th>Unit Cost</th>
				<th>Discount</th>
				<th>Paid Via</th>
				<th>Last Modified</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody class="tbody">
			<?php
			$formater = new NumberFormatter($locale, NumberFormatter::CURRENCY);
			foreach($data as $info){?>
				<tr>
					<td><?=ucwords("$info->product")?></td>
					<td><?=$info->quantity?></td>
					<td><?=$formater->formatCurrency($info->cost_per_item, $user->currency_code)?></td>
					<td><?=$formater->formatCurrency($info->discount, $user->currency_code)?></td>
					<td><?=ucwords("$info->method")?></td>
					<td><?=$this->time->format_date($info->modified_date,"d M, Y &#8226 h:iA")?></td>
					<td><?=ucwords($info->status)?></td>
				</tr>
			<?php }?>
		</tbody>
	</table>
</div>