<div class="p-2 table-responsive">
	<table class="table table-bordered table-striped-even header-text" align="center">
		<caption class="font-sm ml-3">List of Products generated by Point Of Sale!</caption>
		<thead class="thead-light">
			<tr>
				<th>Product Name</th>
				<th>Category</th>
				<th>Cost</th>
				<th>Status</th>
				<th>Last Change</th>
			</tr>
		</thead>
		<tbody class="tbody">
			<?php
			$formater = new NumberFormatter($locale, NumberFormatter::CURRENCY);
			foreach($data as $info){?>
				<tr>
					<td><?=ucwords("$info->product")?></td>
					<td><?=ucwords("$info->category_name")?></td>
					<td><?=$formater->formatCurrency($info->cost_per_unit, $user->currency_code)?></td>
					<td><?=$info->status?></td>
					<td><?=$this->time->format_date($info->modified_date,"d M, Y &#8226 h:iA")?></td>
				</tr>
			<?php }?>
		</tbody>
	</table>
</div>